if(NOT DEFINED ASSET_DIR)
  message(FATAL_ERROR "ASSET_DIR is required")
endif()
if(NOT DEFINED OUT_CPP)
  message(FATAL_ERROR "OUT_CPP is required")
endif()

function(detect_mime path out_var)
  get_filename_component(ext "${path}" EXT)
  string(TOLOWER "${ext}" ext)

  if(ext STREQUAL ".html")
    set(mime "text/html; charset=utf-8")
  elseif(ext STREQUAL ".css")
    set(mime "text/css; charset=utf-8")
  elseif(ext STREQUAL ".js" OR ext STREQUAL ".mjs")
    set(mime "application/javascript; charset=utf-8")
  elseif(ext STREQUAL ".json")
    set(mime "application/json; charset=utf-8")
  elseif(ext STREQUAL ".webmanifest")
    set(mime "application/manifest+json; charset=utf-8")
  elseif(ext STREQUAL ".svg")
    set(mime "image/svg+xml")
  elseif(ext STREQUAL ".png")
    set(mime "image/png")
  elseif(ext STREQUAL ".jpg" OR ext STREQUAL ".jpeg")
    set(mime "image/jpeg")
  elseif(ext STREQUAL ".gif")
    set(mime "image/gif")
  elseif(ext STREQUAL ".ico")
    set(mime "image/x-icon")
  elseif(ext STREQUAL ".woff")
    set(mime "font/woff")
  elseif(ext STREQUAL ".woff2")
    set(mime "font/woff2")
  else()
    set(mime "application/octet-stream")
  endif()

  set(${out_var} "${mime}" PARENT_SCOPE)
endfunction()

get_filename_component(out_dir "${OUT_CPP}" DIRECTORY)
file(MAKE_DIRECTORY "${out_dir}")

set(asset_files)
if(EXISTS "${ASSET_DIR}")
  file(GLOB_RECURSE asset_files RELATIVE "${ASSET_DIR}" "${ASSET_DIR}/*")
endif()
list(SORT asset_files)

set(array_defs "")
set(map_entries "")
set(has_assets FALSE)
set(has_index FALSE)
set(index 0)

foreach(asset IN LISTS asset_files)
  set(full_path "${ASSET_DIR}/${asset}")
  if(IS_DIRECTORY "${full_path}")
    continue()
  endif()

  set(has_assets TRUE)
  string(REPLACE "\\" "/" normalized "${asset}")
  if(normalized STREQUAL "index.html")
    set(has_index TRUE)
  endif()

  file(READ "${full_path}" hex_content HEX)
  set(byte_list "")
  if(NOT hex_content STREQUAL "")
    string(REGEX REPLACE "([0-9A-Fa-f][0-9A-Fa-f])" "0x\\1," byte_list "${hex_content}")
  endif()

  set(symbol "kAsset_${index}")
  detect_mime("${normalized}" mime)

  string(APPEND array_defs "static const unsigned char ${symbol}[] = {${byte_list}};\n")
  string(APPEND map_entries "    {\"/${normalized}\", {\"${mime}\", std::string_view(reinterpret_cast<const char*>(${symbol}), sizeof(${symbol}))}},\n")

  math(EXPR index "${index} + 1")
endforeach()

if(NOT has_assets)
  string(APPEND map_entries "    {\"/index.html\", {\"text/html; charset=utf-8\", kFallbackHtml}},\n")
elseif(NOT has_index)
  string(APPEND map_entries "    {\"/index.html\", {\"text/html; charset=utf-8\", kFallbackHtml}},\n")
endif()

set(generated_cpp "")
string(APPEND generated_cpp "#include \"ferryman/web/EmbeddedAssets.hpp\"\n")
string(APPEND generated_cpp "#include <string_view>\n")
string(APPEND generated_cpp "#include <unordered_map>\n\n")
string(APPEND generated_cpp "namespace ferryman::web {\n")
string(APPEND generated_cpp "namespace {\n")
string(APPEND generated_cpp "static constexpr std::string_view kFallbackHtml = R\"HTML(<!doctype html><html><head><meta charset=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"/><title>Ferryman</title><style>body{font-family:ui-sans-serif,system-ui,-apple-system,sans-serif;background:#0f172a;color:#e2e8f0;margin:0;padding:2rem}code{background:#1e293b;padding:.2rem .4rem;border-radius:.4rem}</style></head><body><h1>Ferryman</h1><p>Frontend dist not found.</p><p>Run <code>make frontend</code> then rebuild backend.</p></body></html>)HTML\";\n")
string(APPEND generated_cpp "${array_defs}")
string(APPEND generated_cpp "}  // namespace\n\n")
string(APPEND generated_cpp "const std::unordered_map<std::string, EmbeddedAsset>& GetEmbeddedAssets() {\n")
string(APPEND generated_cpp "  static const std::unordered_map<std::string, EmbeddedAsset> kAssets = {\n")
string(APPEND generated_cpp "${map_entries}")
string(APPEND generated_cpp "  };\n")
string(APPEND generated_cpp "  return kAssets;\n")
string(APPEND generated_cpp "}\n\n")
string(APPEND generated_cpp "}  // namespace ferryman::web\n")

set(existing_cpp "")
if(EXISTS "${OUT_CPP}")
  file(READ "${OUT_CPP}" existing_cpp)
endif()

if(NOT existing_cpp STREQUAL generated_cpp)
  file(WRITE "${OUT_CPP}" "${generated_cpp}")
endif()
